### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by cforce** [pivotal-cf/docs-a9s-bosh#11]
Please support Azure IAAS

**Comment by pspinrad** [comment]
Forwarding request to svc.support@anynines.com

**Comment by gogolok** [comment]
Hey @cforce,

support for Azure IaaS is on our roadmap.
Please provide any feature requests or questions to svc.support@anynines.com
Thanks in advance!

Best regards,
Robert


--
anynines.com 

Avarteq GmbH
Platform Engineer
Twitter: @anynines

----
Geschäftsführer: Alexander Faißt, Dipl.-Inf.(FH) Julian Fischer
Handelsregister: AG Saarbrücken HRB 17413, Ust-IdNr.: DE262633168
Sitz: Saarbrücken
